# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

In [ ]:
import numpy as np

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
data1 = np.linspace(0, 20, 28).reshape(4, 7)
masiv_read1 = (data1 - np.min(data1)) / (np.max(data1) - np.min(data1))
print(masiv_read1)

[[0.         0.03703704 0.07407407 0.11111111 0.14814815 0.18518519
  0.22222222]
 [0.25925926 0.2962963  0.33333333 0.37037037 0.40740741 0.44444444
  0.48148148]
 [0.51851852 0.55555556 0.59259259 0.62962963 0.66666667 0.7037037
  0.74074074]
 [0.77777778 0.81481481 0.85185185 0.88888889 0.92592593 0.96296296
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
matric = np.random.randint(0, 11, (8,10))
print(np.argsort(matric.sum(axis = 1))[0])

5


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
vectors = np.random.randint(0, 11, (2, 4))
print(np.linalg.norm(vectors[1] - vectors[0]))

12.767145334803704


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(np.linalg.inv(a) @ (c * (-1)) @ np.linalg.inv(b))

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
a = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)
print(a[:5])

FileNotFoundError: ignored

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print('Среднее значение 2 столбца:', np.mean(a[:,1]))
print('Среднее значение 3 столбца:', np.mean(a[:,2]))
print('Минимальное значение 2 столбца:', np.min(a[:,1]))
print('Минимальное значение 3 столбца:', np.min(a[:,2]))
print('Максимальное значение 2 столбца:', np.max(a[:,1]))
print('Максимальное значение 3 столбца:', np.max(a[:,2]))
print('Медиана 2 столбца:', np.median(a[:,1]))
print('Медиана 3 столбца:', np.median(a[:,2]))

Среднее значение 2 столбца: 21601.00169
Среднее значение 3 столбца: 9.05528
Минимальное значение 2 столбца: 0
Минимальное значение 3 столбца: 1
Максимальное значение 2 столбца: 2147483647
Максимальное значение 3 столбца: 39
Медиана 2 столбца: 40.0
Медиана 3 столбца: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
d = a.copy()
quant = np.quantile(d[:, 1], .75)
d[d[:, 1] > quant] = quant
print(d)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [    65     65     65]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
a1 = a.copy()
print(np.count_nonzero(a1[:,1] == 0))
a[a1[:,1] == 0] = 1
print(a)

479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
a1 = a.copy()
np.unique (a1[: ,0])
print(np.unique(a1[:,0]).size)


99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
a1 = a.copy()
print(np.unique(a1[:, 2]).size)
print(np.unique(a1[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
a1 = a.copy()
v = a1[a1[:, 2] <= 5] 
print(v)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
a1 = a.copy()
m = a1[:, 2] / a1[:, 1]
print(m.max())
print(m)


23.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
a1 = a.copy()
n = np.argsort(a[:, 1])[-100:]
print(np.mean(a[n][:, 2]))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
a1 = a.copy()
print(a1[np.random.randint(0, a1.shape[0], 10)])

[[448236     50     14]
 [254819     80     12]
 [424721    486      9]
 [280474     80      8]
 [408013     40      6]
 [ 20732     22      7]
 [454922    150     18]
 [153723     25      7]
 [336669     30      7]
 [261381     65     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
a1 = a.copy()
sred = np.mean(a1[:, 2])
print((np.count_nonzero(a1[:, 2] < sred) * 100) / a.shape[0])

58.989


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

NameError: ignored

13. Выведите процент "простых" рецептов в датасете

NameError: ignored

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
a1 = a.copy()
mal = a1[a1[:, 1] < 10]
stand = a1[(a1[:, 1] >= 10) & (a1[:, 1] < 20)]
bol = a1[a1[:, 1] >= 20]
massiv = np.min([mal.shape[0], stand.shape[0], bol.shape[0]])
mas_max = np.array([mal[:massiv], stand[:massiv], bol[:massiv]])
print(mas_max)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [     1      1      1]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
